description: "A new Flutter application."
name: "flutterapp"
publish_to: "none"
version: "1.0.0+1"
dependencies: 
  cupertino_icons: "^0.1.3"
  path_drawing: "^0.4.1"
  flutter: 
    sdk: "flutter"
dev_dependencies: 
  flutter_test: 
    sdk: "flutter"
environment: 
  sdk: ">=2.7.0 <3.0.0"
flutter: 
  assets: 
    - "assets/images/"
  fonts: 
    - 
      family: "Montserrat"
      fonts: 
        - 
          asset: "fonts/Montserrat-500.ttf"
          style: "normal"
          weight: 500
        - 
          asset: "fonts/Montserrat-600.ttf"
          style: "normal"
          weight: 600
        - 
          asset: "fonts/Montserrat-regular.ttf"
          style: "normal"
          weight: 400
    - 
      family: "Mulish"
      fonts: 
        - 
          asset: "fonts/Mulish-600.ttf"
          style: "normal"
          weight: 600
        - 
          asset: "fonts/Mulish-500.ttf"
          style: "normal"
          weight: 500
    - 
      family: "Lato"
      fonts: 
        - 
          asset: "fonts/Lato-700.ttf"
          style: "normal"
          weight: 700
    - 
      family: "DM Sans"
      fonts: 
        - 
          asset: "fonts/DMSans-regular.ttf"
          style: "normal"
          weight: 400
        - 
          asset: "fonts/DMSans-700.ttf"
          style: "normal"
          weight: 700
        - 
          asset: "fonts/DMSans-500.ttf"
          style: "normal"
          weight: 500
  uses-material-design: true
