import 'package:flutter/material.dart';
import 'package:flutterapp/messageappapp/generatedchatscreenwidget/generated/GeneratedIPhoneXHomeIndicatorHomeIndicatorOnLightWidget.dart';
import 'package:flutterapp/messageappapp/generatedchatscreenwidget/generated/GeneratedFrame3268Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/messageappapp/generatedchatscreenwidget/generated/GeneratedTimeStyleWidget.dart';

/* Frame Chat Screen
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedChatScreenWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 926.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 27.0,
                              top: 881.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 34.0,
                              child:
                                  GeneratedIPhoneXHomeIndicatorHomeIndicatorOnLightWidget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: null,
                              right: 0.0,
                              bottom: null,
                              width: null,
                              height: 56.0,
                              child: TransformHelper.translate(
                                  x: 0.00,
                                  y: 389.00,
                                  z: 0,
                                  child: LayoutBuilder(builder:
                                      (BuildContext context,
                                          BoxConstraints constraints) {
                                    final double width = constraints.maxWidth *
                                        0.8761682242990654;

                                    return Stack(children: [
                                      TransformHelper.translate(
                                          x: constraints.maxWidth *
                                              0.07710280373831775,
                                          y: 0,
                                          z: 0,
                                          child: Container(
                                            width: width,
                                            child: GeneratedFrame3268Widget(),
                                          ))
                                    ]);
                                  })),
                            ),
                            Positioned(
                              left: 4.0,
                              top: 1.3333001136779785,
                              right: null,
                              bottom: null,
                              width: 54.0,
                              height: 21.0,
                              child: GeneratedTimeStyleWidget(),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
