import 'package:flutter/material.dart';
import 'package:flutterapp/messageappapp/generatedconversationwidget/generated/GeneratedIPhoneXHomeIndicatorHomeIndicatorOnLightWidget1.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/messageappapp/generatedconversationwidget/generated/GeneratedIconGroupWidget1.dart';
import 'package:flutterapp/messageappapp/generatedconversationwidget/generated/GeneratedMainContainerWidget.dart';
import 'package:flutterapp/messageappapp/generatedconversationwidget/generated/GeneratedTopBarWidget1.dart';
import 'package:flutterapp/messageappapp/generatedconversationwidget/generated/GeneratedTimeStyleWidget1.dart';
import 'package:flutterapp/messageappapp/generatedconversationwidget/generated/GeneratedBottomBarWidget.dart';

/* Frame Conversation
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedConversationWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: LayoutBuilder(
          builder: (BuildContext context, BoxConstraints constraints) {
        return SingleChildScrollView(
          scrollDirection: Axis.vertical,
          child: Container(
              height: 926.0,
              child: Stack(children: [
                Container(
                    width: constraints.maxWidth,
                    child: Container(
                      width: 428.0,
                      height: 926.0,
                      child: Stack(
                          fit: StackFit.expand,
                          alignment: Alignment.center,
                          overflow: Overflow.visible,
                          children: [
                            ClipRRect(
                              borderRadius: BorderRadius.zero,
                              child: Container(
                                color: Color.fromARGB(255, 255, 255, 255),
                              ),
                            ),
                            Positioned(
                              left: 27.0,
                              top: 881.0,
                              right: null,
                              bottom: null,
                              width: 375.0,
                              height: 34.0,
                              child:
                                  GeneratedIPhoneXHomeIndicatorHomeIndicatorOnLightWidget1(),
                            ),
                            Positioned(
                              left: 4.0,
                              top: 1.3333001136779785,
                              right: null,
                              bottom: null,
                              width: 54.0,
                              height: 21.0,
                              child: GeneratedTimeStyleWidget1(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.8878504672897196;

                                final double height =
                                    constraints.maxHeight * 0.09719222462203024;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: 0,
                                      y: constraints.maxHeight *
                                          0.028077753779697623,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedTopBarWidget1(),
                                      ))
                                ]);
                              }),
                            ),
                            Positioned(
                              left: 376.0,
                              top: 47.0,
                              right: null,
                              bottom: null,
                              width: 24.0,
                              height: 24.0,
                              child: GeneratedIconGroupWidget1(),
                            ),
                            Positioned(
                              left: 15.0,
                              top: 69.0,
                              right: null,
                              bottom: null,
                              width: 436.0,
                              height: 730.0,
                              child: GeneratedMainContainerWidget(),
                            ),
                            Positioned(
                              left: 0.0,
                              top: 0.0,
                              right: 0.0,
                              bottom: 0.0,
                              width: null,
                              height: null,
                              child: LayoutBuilder(builder:
                                  (BuildContext context,
                                      BoxConstraints constraints) {
                                final double width =
                                    constraints.maxWidth * 0.8761682242990654;

                                final double height =
                                    constraints.maxHeight * 0.08963282937365011;

                                return Stack(children: [
                                  TransformHelper.translate(
                                      x: constraints.maxWidth *
                                          0.056074766355140186,
                                      y: constraints.maxHeight *
                                          0.8801295896328294,
                                      z: 0,
                                      child: Container(
                                        width: width,
                                        height: height,
                                        child: GeneratedBottomBarWidget(),
                                      ))
                                ]);
                              }),
                            )
                          ]),
                    ))
              ])),
        );
      }),
    ));
  }
}
